INHERIT: ../base.yml
site_name: Diseño de Interfaces Web - Proyectos
site_dir: ../../docs/proyectos
  

# Page tree
nav:
  - Inicio: index.md
  - Proyecto 1: proyecto1.md
  #- Proyecto 2: proyecto2.md


extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/IESAlbertiCadiz
      name: IES Rafael Alberti en Twitter
